name: talkifyapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  cached_network_image: ^3.3.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  rename: ^3.0.1
  permission_handler: ^12.0.0+1
  uuid: ^4.2.2
  image_picker: ^1.0.5
  intl: ^0.20.2
  pie_chart: ^5.4.0
  audioplayers: ^6.4.0
  just_audio: ^0.9.36
  clipboard: ^0.1.3
  flutter_markdown: ^0.7.7+1

  vibration: ^3.1.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_local_notifications: ^19.2.1
  record: ^6.0.0
  flutter_animation_progress_bar: ^2.3.1
  file_picker: ^10.1.9
  device_info_plus: ^11.3.0
  url_launcher: ^6.2.2
  photo_view: ^0.15.0
  connectivity_plus: ^6.1.4
  share_plus: ^11.0.0
  flutter_sound: ^9.2.13
  dotted_border: ^2.1.0
  camera: ^0.11.0+2
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.9
  animated_text_kit: ^4.2.2
  emoji_picker_flutter: ^4.3.0
  lottie: ^3.2.0
  provider: ^6.1.1
  geolocator: ^10.1.0
  dropdown_button2: ^2.3.9
  flutter_image_compress: ^2.1.0
  gif_view: ^1.0.3
  lazy_load_scrollview: ^1.3.0
  circular_countdown_timer: ^0.2.3
  percent_indicator: ^4.2.3
  image_cropper: ^9.1.0
  timeago: ^3.6.0
  giphy_picker: ^3.0.1
  flutter_native_splash: ^2.4.0
  photo_manager: ^3.0.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/Logo1.png
    - lib/assets/logo_animation.json
    - lib/assets/Register.json
    - lib/assets/Verfiy.json
    - lib/assets/Search.json
    - lib/assets/profile.json
    - lib/assets/Logo5.json
    - lib/assets/notification.wav
    - lib/assets/