// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGCeFgv1LatH5HwobhhQoLEQ8QFTJbQ94',
    appId: '1:76330742329:web:5c9c1d5b0e73757ee353e8',
    messagingSenderId: '76330742329',
    projectId: 'talkify-4ddbd',
    authDomain: 'talkify-4ddbd.firebaseapp.com',
    storageBucket: 'talkify-4ddbd.firebasestorage.app',
    measurementId: 'G-7TST3HV82N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzW-QT1OTYCW3BCW_3cWESjyth1HLmJ_g',
    appId: '1:76330742329:android:be58a096d56ede36e353e8',
    messagingSenderId: '76330742329',
    projectId: 'talkify-4ddbd',
    storageBucket: 'talkify-4ddbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM6n8CIhujtz_zXQ4VXd_ItDOyMWBy9fY',
    appId: '1:76330742329:ios:e28e5af869bc131ce353e8',
    messagingSenderId: '76330742329',
    projectId: 'talkify-4ddbd',
    storageBucket: 'talkify-4ddbd.firebasestorage.app',
    iosBundleId: 'com.example.talkifyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM6n8CIhujtz_zXQ4VXd_ItDOyMWBy9fY',
    appId: '1:76330742329:ios:e28e5af869bc131ce353e8',
    messagingSenderId: '76330742329',
    projectId: 'talkify-4ddbd',
    storageBucket: 'talkify-4ddbd.firebasestorage.app',
    iosBundleId: 'com.example.talkifyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGCeFgv1LatH5HwobhhQoLEQ8QFTJbQ94',
    appId: '1:76330742329:web:9d3e9f636100f7e7e353e8',
    messagingSenderId: '76330742329',
    projectId: 'talkify-4ddbd',
    authDomain: 'talkify-4ddbd.firebaseapp.com',
    storageBucket: 'talkify-4ddbd.firebasestorage.app',
    measurementId: 'G-WMQPZP4279',
  );
}
