// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH8r_-5WvOYUFtgUGOOu40Ce94eFDZJI4',
    appId: '1:898874309624:web:a0905d9462ab14ace6340d',
    messagingSenderId: '898874309624',
    projectId: 'talkify-edited',
    authDomain: 'talkify-edited.firebaseapp.com',
    storageBucket: 'talkify-edited.firebasestorage.app',
    measurementId: 'G-PRNYD66NZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOFAO7CoEjoq61gHP7DnHUdDUTJZZ8jso',
    appId: '1:898874309624:android:6e9c77a9aabc645ae6340d',
    messagingSenderId: '898874309624',
    projectId: 'talkify-edited',
    storageBucket: 'talkify-edited.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBv-ImP9L6Be-qcfNwxwT0NjKO25RM6gY',
    appId: '1:898874309624:ios:f2045b3a9998c676e6340d',
    messagingSenderId: '898874309624',
    projectId: 'talkify-edited',
    storageBucket: 'talkify-edited.firebasestorage.app',
    iosBundleId: 'com.example.talkifyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBv-ImP9L6Be-qcfNwxwT0NjKO25RM6gY',
    appId: '1:898874309624:ios:f2045b3a9998c676e6340d',
    messagingSenderId: '898874309624',
    projectId: 'talkify-edited',
    storageBucket: 'talkify-edited.firebasestorage.app',
    iosBundleId: 'com.example.talkifyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH8r_-5WvOYUFtgUGOOu40Ce94eFDZJI4',
    appId: '1:898874309624:web:0f8818cdbe9f46d4e6340d',
    messagingSenderId: '898874309624',
    projectId: 'talkify-edited',
    authDomain: 'talkify-edited.firebaseapp.com',
    storageBucket: 'talkify-edited.firebasestorage.app',
    measurementId: 'G-PR15J43D9C',
  );

}